# Generated by Django 6.1 on 2026-09-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_course_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester', 'name']},
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.SmallIntegerField(default=3),
        ),
    ]
