# Generated by Django 6.1 on 2026-09-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_course_options_alter_course_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
